### ISSUE TITLE
运行错误请问什么原因？

### ISSUE THREAD

**Issue by scholar1989** [FullerHua/gooseeker#1]
Traceback (most recent call last):
  File "C:\Users\schol\documents\visual studio 2015\Projects\PythonApplication2\PythonApplication2\PythonApplication2.py", line 16, in <module>
    result = bbsExtra.extract(doc)   # 调用extract方法提取所需内容
  File "C:\Users\schol\documents\visual studio 2015\Projects\PythonApplication2\PythonApplication2\gooseeker.py", line 44, in extract
    transform = etree.XSLT(xslt_root)
  File "xslt.pxi", line 412, in lxml.etree.XSLT.__init__ (src\lxml\lxml.etree.c:173326)
lxml.etree.XSLTParseError: Cannot parse stylesheet
Press any key to continue . . .

**Comment by gz51837844** [comment]
是无效的xslt引起的

**Comment by ipfono** [comment]
尝试在代码中加上 print(bbsExtra.getXslt()) 打印一下返回的XSLT 内容，看看是否正确。XSLT获取方式是直接变量赋值还是API 获取呢？若为API 获取，需要检查一下参数是否正确。
检查方式：可直接访问API入口网址（加上参数）看看是否能返回正确的xslt
