### ISSUE TITLE
安居客得爬取出现错误，是网站作了防范吗

### ISSUE THREAD

**Issue by YaphetsH** [FullerHua/gooseeker#3]
爬取开始
正在爬取 http://shenzhen.anjuke.com/tycoon/nanshan/p1
Traceback (most recent call last):
  File "anjuke.py", line 34, in <module>
    content = anjukeSpider.getContent(currenturl)
  File "anjuke.py", line 11, in getContent
    conn = request.urlopen(url)
  File "E:\Python3.5\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python3.5\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "E:\Python3.5\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Python3.5\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "E:\Python3.5\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "E:\Python3.5\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "E:\Python3.5\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "E:\Python3.5\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Python3.5\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "E:\Python3.5\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "E:\Python3.5\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by ipfono** [comment]
应该是的，可以尝试用urllib2设置一下header模仿浏览器发出请求或用selenium驱动浏览器爬取

**Comment by dengwen168** [comment]
我和上面出现一模一样的错误，我还以为我的程序在哪儿出了问题。
